name: ChatCoPlus
version: '${project.version}'
main: org.zeroBzeroT.chatCo.Main
api-version: '1.20'
depend: [ProtocolLib]
authors: [0xB2]
description: A simple chat plugin
website: https://github.com/0xB2
folia-supported: true
commands:
  togglechat:
    description: Enables or disables chat for the player.
    usage: /toggleechat
  toggletells:
    description: Enables or disables whispers for the player.
    usage: /toggletells
  ignore:
    description: Allows a player to ignore another player.
    usage: /ignore <playername>
  unignoreall:
    description: Removes all entries from a players ignore list.
    usage: /unignoreall
  ignorelist:
    description: Returns a list of all currently ignored players.
    usage: /ignorelist
  chatco:
    description: Enables or disables whispers and spoilers. Only console input accepted. 'e' enables, 'd' disables.
    usage: /chatco <whispers|spoilers|newcommands|whisperlog> <e|d>
  whisper:
    description: Allows a player to whisper another player
    usage: /whisper or /w to whisper another player
  bed:
    description: Allows you to see where your bed is set
    usage: /bed to see the bed location
  tell:
    description: Allows a player to whisper another player
    usage: /whisper or /w to whisper another player
  msg:
    description: Allows a player to whisper another player
    usage: /whisper or /w to whisper another player
  message:
    description: Allows a player to whisper another player
    usage: /whisper or /w to whisper another player
  suicide:
    description: Allows a player to commit seppuku
    usage: /suicide or /kill
  w:
    description: Allows a player to whisper another player
    usage: /whisper or /w to whisper another player
  reply:
    description: Allows a player to reply to the last received message
    usage: /reply or /r to reply to your last message
  r:
    description: Allows a player to reply to the last received message
    usage: /reply or /r to reply to your last message
  blackhole:
    description: Nonya
    usage: /blackhole <player name>
permissions:
  ChatCo.chatPrefixes.GREEN:
    description: Allows you to use to use Green prefixes in chat
    default: false
  ChatCo.chatPrefixes.BLUE:
    description: Allows you to use to use Blue prefixes in chat
    default: false
  ChatCo.chatPrefixes.RED:
    description: Allows you to use to use Red prefixes in chat
    default: false
  ChatCo.chatPrefixes.AQUA:
    description: Allows you to use to use Aqua prefixes in chat
    default: false
  ChatCo.chatPrefixes.GOLD:
    description: Allows you to use to use Gold prefixes in chat
    default: false
  ChatCo.chatPrefixes.YELLOW:
    description: Allows you to use to use Yellow prefixes in chat
    default: false
  ChatCo.chatPrefixes.GRAY:
    description: Allows you to use to use Gray prefixes in chat
    default: false
  ChatCo.chatPrefixes.BLACK:
    description: Allows you to use to use Black prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_GREEN:
    description: Allows you to use to use Dark_Green prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_RED:
    description: Allows you to use to use Dark_Red prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_GRAY:
    description: Allows you to use to use Dark_Gray prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_BLUE:
    description: Allows you to use to use Dark_Blue prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_AQUA:
    description: Allows you to use to use Dark_Aqua prefixes in chat
    default: false
  ChatCo.chatPrefixes.DARK_PURPLE:
    description: Allows you to use to use Dark_Purple prefixes in chat
    default: false
  ChatCo.chatPrefixes.LIGHT_PURPLE:
    description: Allows you to use to use Light_Purple prefixes in chat
    default: false
  ChatCo.chatColors..GREEN:
    description: Allows you to use to use Green colors in chat
    default: false
  ChatCo.chatColors..BLUE:
    description: Allows you to use to use Blue colors in chat
    default: false
  ChatCo.chatColors..RED:
    description: Allows you to use to use Red colors in chat
    default: false
  ChatCo.chatColors..AQUA:
    description: Allows you to use to use Aqua colors in chat
    default: false
  ChatCo.chatColors..GOLD:
    description: Allows you to use to use Gold colors in chat
    default: false
  ChatCo.chatColors..YELLOW:
    description: Allows you to use to use Yellow colors in chat
    default: false
  ChatCo.chatColors..GRAY:
    description: Allows you to use to use Gray colors in chat
    default: false
  ChatCo.chatColors..BLACK:
    description: Allows you to use to use Black colors in chat
    default: false
  ChatCo.chatColors..DARK_GREEN:
    description: Allows you to use to use Dark_Green colors in chat
    default: false
  ChatCo.chatColors..DARK_RED:
    description: Allows you to use to use Dark_Red colors in chat
    default: false
  ChatCo.chatColors..DARK_GRAY:
    description: Allows you to use to use Dark_Gray colors in chat
    default: false
  ChatCo.chatColors..DARK_BLUE:
    description: Allows you to use to use Dark_Blue colors in chat
    default: false
  ChatCo.chatColors..DARK_AQUA:
    description: Allows you to use to use Dark_Aqua colors in chat
    default: false
  ChatCo.chatColors..DARK_PURPLE:
    description: Allows you to use to use Dark_Purple colors in chat
    default: false
  ChatCo.chatColors..LIGHT_PURPLE:
    description: Allows you to use to use Light_Purple colors in chat
    default: false