name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache
        uses: actions/cache@v4.2.4
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get Project Info
        run: |
          echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}.${{ github.run_number }}
          name: Release ${{ env.VERSION }} Build ${{ github.run_number }}
          draft: false
          prerelease: true
          latest: false
          files: |
            target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar
            target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}-sources.jar